### ISSUE TITLE
Failing to find behaviors after switching to 0.5.1

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-build#85]
### Description
After switching from 0.5.0 to 0.5.1 I have following errors:
```
[36minit_1   |[0m [31merror[39m:   In vendor/neon-animation/neon-animation-runner-behavior.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimatableBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/neon-animation/animations/fade-in-animation.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimationBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/neon-animation/animations/fade-out-animation.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimationBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/iron-selector/iron-multi-selectable.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.IronSelectableBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/neon-animation/animations/opaque-animation.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimationBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-menu-button/paper-menu-button-animations.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimationBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-menu-button/paper-menu-button-animations.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimationBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-menu-button/paper-menu-button-animations.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimationBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-menu-button/paper-menu-button-animations.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimationBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-input/paper-input.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.IronFormElementBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-input/paper-input.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.PaperInputBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/iron-lazy-pages/iron-lazy-pages.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.IronLazyPagesBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-dialog/paper-dialog.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.PaperDialogBehavior`. Did you import it? Is it annotated with @polymerBehavior?
[36minit_1   |[0m [31merror[39m:   In vendor/paper-input/paper-input-error.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.PaperInputAddonBehavior`. Did you import it? Is it annotated with @polymerBehavior?
```

Project structure:

```
src/
  index.html
vendor/             # bower_components
bower.json
```
polymer.json: 
```
{
    "entrypoint": "src/index.html",
    "shell": "src/components/app/bi-app/bi-app.html",
    "fragments": [
        "src/components/pages/bi-404/bi-404-page.html", # etc
        ...
    ],
    "sources": [
        "src/**/*"
    ]
}
```

### Versions & Environment
- polymer-build: 0.5.1
- node: 6.9.1 
- Operating System: Mac OS El Capitan 10.11.5

Please pay attention that `vendor` (bower components dir) is outside of `src`. Not sure if this is the reason. In local env, I mount both directories into docker container as volumes, and I have a symlink `src/vendor` which points to `vendor`.

Adding `bower.json` to `sources` doesn't help.

**Comment by web-padawan** [comment]
UPD: modifying sources fixed the issue. 
```
    "sources": [
        "vendor/**/*",
        "src/components/**/*"
    ]
```
For now I'll keep this opened, please close if this not a build / analyzer issue (e. g. my previous config was wrong and my build only used to pass by accident).

**Comment by justinfagnani** [comment]
I bet it's that you're using `vendor` rather than `bower_components`. Not sure that we've threaded through a components dir setting yet.

**Comment by web-padawan** [comment]
Good point. Looks like the config from `.bowerrc` should be passed [here](https://github.com/Polymer/polymer-analyzer/blob/11776c31aa1d4f19152095fce8bc6528ef99fa93/src/url-loader/package-url-resolver.ts#L34).

**Comment by FredKSchott** [comment]
Yea, by including the entire vendor directory in `sources` or `extraDependencies` will cause the entire directory to be included in build, including all metadata (READMEs, tests, etc).

`vendor` instead of `bower_components` should not be an issue, since you're application imports explicitly point to `vendor`, right?

The only thing that changed between 0.5.0->0.5.1 is an update to polymer-analyzer. The CHANGELOG mentions a few behavior-related fixes, my guess is that a regression was introduced there. /cc @rictic

**Comment by FredKSchott** [comment]
@web-padawan is the application available anywhere for us to test on? Do you have a simple reproduction case that you can share?

**Comment by web-padawan** [comment]
Yes, my app imports from `vendor` using relative paths.
Code is not public, but I'll try to make a small reproduction this week.

**Comment by FredKSchott** [comment]
@web-padawan can you remove js minification from your build pipeline and try again? 0.5.x currently has a problem where minification removes type annotations from your final application.

**Comment by FredKSchott** [comment]
Arg, I can reproduce this now. Confirmed that the analyzer is incorrectly reporting missing behavior annotations when they do exist (while taking another look at https://github.com/GDGSpain/gdg.es/pull/34). 

I'll look into this in polymer-analyzer now. /cc @rictic

**Comment by FredKSchott** [comment]
Update: @rictic already has a fix in progress, we are working on getting it merged now.

**Comment by abdonrd** [comment]
I have the same issue! Any news on this? :)

**Comment by FredKSchott** [comment]
@abdonrd yes! This was fixed on master with the analyze-first work. It's available today via the `next` tag (`npm install poylmer-build@next --save-dev`), and we hope to get it pushed out broadly in the next few days.

**Comment by web-padawan** [comment]
Need to stamp `polymer-analyzer` 2.0.0-alpha20 and `polymer-build` 0.6.0 to have this fixed, right?

**Comment by FredKSchott** [comment]
It's fixed in the polymer-build v0.6.0 prerelease, available today via `npm i polymer-build@next`. We'll be stamping v0.6.0 soon.

**Comment by web-padawan** [comment]
Thanks! Will upgrade once it will be stamped.
Right now, installing `npm i polymer-build@next` still resolves to `polymer-analyzer@2.0.0-alpha.18`.

**Comment by FredKSchott** [comment]
Yup, but it should be fixed anyway. The `polymer-analyzer` issue had to do with parallel analysis, which we removed from `polymer-build` in v0.6.0. Try running again and let me know if you're still seeing issues resolving behaviors.

**Comment by Sinjins** [comment]
FYI, even after installing _polymer-build@next_ I'm still seeing issues resolving behaviors.  Specifically, I'm using app-localize-behavior in many of my custom elements.

**Comment by rictic** [comment]
@Sinjins Do you have a link to a file/project that's giving that warning?

**Comment by Sinjins** [comment]
@rictic code isn't public, but I'm using GULP, and an exact replica of gulpfile.js used by [https://github.com/PolymerElements/generator-polymer-init-custom-build](url)

**Comment by rictic** [comment]
Hm, tricky to remote debug without the code or a public repro. Do the elements import app-localize-behavior.html? Do they reference it as anything other than PolymerAppLocalizeBehavior?

**Comment by Sinjins** [comment]
@rictic yes, sorry bout that.  Each of the elements do indeed import app-localize-behavior, and then implement them as follows:

`<link rel="import" href="../bower_components/app-localize-behavior/app-localize-behavior.html">`

`behaviors: [
            Polymer.AppLocalizeBehavior
]`

**Comment by Sinjins** [comment]
FYI, I just updated to the latest polymer-build (v 0.8.1) and now I receive the following 'warning' message during gulp build:  

>  [could-not-determine-behavior-name] - Could not determine behavior name from expression of type CallExpression

**Comment by Bunny2242** [comment]
[unknown-polymer-behavior] - Unable to resolve behavior `Polymer.NeonAnimatableBehavior`. Did you import it? Is it annotated with @polymerBehavior?


I Have been facing this issue while making build.Can any one help me.

**Comment by FredKSchott** [comment]
@Bunny2242 you're probably using an old version of the CLI, or you aren't properly importing that behavior.

Join the #general or #tools channels on [Slack](https://polymer-slack.herokuapp.com/) if you're interested in more help using Polymer & Polymer tools.

**Comment by Bunny2242** [comment]
@FredKSchott  
I have included like mentioned below. is this wrong?.

 Polymer({
    is: 'my-app',
    behaviors: [
        Polymer.NeonAnimatableBehavior,
        Polymer.NeonAnimationBehavior,
        Polymer.NeonAnimationRunnerBehavior,
    ]
});

**Comment by rictic** [comment]
@Bunny2242  That should work, provided that you have imports for the proper files in your element. Something like the following:

```html
<link rel="import" href="../neon-animation/neon-animatable-behavior.html">
<link rel="import" href="../neon-animation/neon-animation-behavior.html">
<link rel="import" href="../neon-animation/neon-animation-runner-behavior.html">
```

**Comment by tsvetan-ganev** [comment]
For those who are making a custom behavior and still get this error although they are importing the corresponding `.html` file:

```html
<script>
    /**
     * @polymerBehavior
     */
    Polymer.MyCustomBehavior = {};
</script>
```

Just add `@polymerBehavior` in a comment directly above the behavior declaration. This fixed the `polymer lint` errors for me.

**Comment by nicholaswmin** [comment]
@tsvetan-ganev 

You also need to include the behaviour name in the annotation:

```html
<script>
    /**
     * @polymerBehavior
     */
    Polymer.MyCustomBehavior = {};
</script>
```

**Comment by web-padawan** [comment]
@nicholaswmin there used to be a bug in analyzer which treated not related comments, e. g eslint instructions, like behaviors annotations. It was fixed in 2.2.0 by assuming that no newline should present there.

**Comment by 8ctopotamus** [comment]
Any fix for this? I still get these warnings on polymer-cli 1.5.4.

Including the behavior name in the annotation didn't fix it.
